//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Domain.Booking {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Booking {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Booking() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resources.Domain.Booking.Booking", typeof(Booking).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string BookingDate {
            get {
                return ResourceManager.GetString("BookingDate", resourceCulture);
            }
        }
        
        public static string BookingEndDay {
            get {
                return ResourceManager.GetString("BookingEndDay", resourceCulture);
            }
        }
        
        public static string BookingNumber {
            get {
                return ResourceManager.GetString("BookingNumber", resourceCulture);
            }
        }
        
        public static string BookingPeriodDays {
            get {
                return ResourceManager.GetString("BookingPeriodDays", resourceCulture);
            }
        }
        
        public static string BookingStartDay {
            get {
                return ResourceManager.GetString("BookingStartDay", resourceCulture);
            }
        }
        
        public static string BookingTotal {
            get {
                return ResourceManager.GetString("BookingTotal", resourceCulture);
            }
        }
        
        public static string BookingWithoutVat {
            get {
                return ResourceManager.GetString("BookingWithoutVat", resourceCulture);
            }
        }
        
        public static string InvoiceId {
            get {
                return ResourceManager.GetString("InvoiceId", resourceCulture);
            }
        }
        
        public static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        public static string ItemOwnerCompanyId {
            get {
                return ResourceManager.GetString("ItemOwnerCompanyId", resourceCulture);
            }
        }
        
        public static string ItemOwnerId {
            get {
                return ResourceManager.GetString("ItemOwnerId", resourceCulture);
            }
        }
        
        public static string PricePerDay {
            get {
                return ResourceManager.GetString("PricePerDay", resourceCulture);
            }
        }
        
        public static string RentalPeriodId {
            get {
                return ResourceManager.GetString("RentalPeriodId", resourceCulture);
            }
        }
        
        public static string RenterCompanyId {
            get {
                return ResourceManager.GetString("RenterCompanyId", resourceCulture);
            }
        }
        
        public static string RenterId {
            get {
                return ResourceManager.GetString("RenterId", resourceCulture);
            }
        }
        
        public static string Vat {
            get {
                return ResourceManager.GetString("Vat", resourceCulture);
            }
        }
        
        public static string VatPercent {
            get {
                return ResourceManager.GetString("VatPercent", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
    }
}
