//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Items {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resources.Views.Items.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string MyItems {
            get {
                return ResourceManager.GetString("MyItems", resourceCulture);
            }
        }
        
        public static string CompanyItems {
            get {
                return ResourceManager.GetString("CompanyItems", resourceCulture);
            }
        }
        
        public static string CreateNewItem {
            get {
                return ResourceManager.GetString("CreateNewItem", resourceCulture);
            }
        }
        
        public static string AddItemDescription {
            get {
                return ResourceManager.GetString("AddItemDescription", resourceCulture);
            }
        }
        
        public static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        public static string AddAddress {
            get {
                return ResourceManager.GetString("AddAddress", resourceCulture);
            }
        }
        
        public static string ChangeCategory {
            get {
                return ResourceManager.GetString("ChangeCategory", resourceCulture);
            }
        }
        
        public static string ChangeImages {
            get {
                return ResourceManager.GetString("ChangeImages", resourceCulture);
            }
        }
        
        public static string ChangeOwnership {
            get {
                return ResourceManager.GetString("ChangeOwnership", resourceCulture);
            }
        }
        
        public static string ChangePrices {
            get {
                return ResourceManager.GetString("ChangePrices", resourceCulture);
            }
        }
        
        public static string ChangeItemDescriptions {
            get {
                return ResourceManager.GetString("ChangeItemDescriptions", resourceCulture);
            }
        }
    }
}
