//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Domain.Item {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Item {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Item() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resources.Domain.Item.Item", typeof(Item).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string LocationId {
            get {
                return ResourceManager.GetString("LocationId", resourceCulture);
            }
        }
        
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        public static string PricePerDay {
            get {
                return ResourceManager.GetString("PricePerDay", resourceCulture);
            }
        }
        
        public static string PricePerWeek {
            get {
                return ResourceManager.GetString("PricePerWeek", resourceCulture);
            }
        }
        
        public static string PricePerMonth {
            get {
                return ResourceManager.GetString("PricePerMonth", resourceCulture);
            }
        }
        
        public static string BookingStartDay {
            get {
                return ResourceManager.GetString("BookingStartDay", resourceCulture);
            }
        }
        
        public static string BookingEndDay {
            get {
                return ResourceManager.GetString("BookingEndDay", resourceCulture);
            }
        }
        
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        public static string CompanyId {
            get {
                return ResourceManager.GetString("CompanyId", resourceCulture);
            }
        }
        
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        public static string CategoryId {
            get {
                return ResourceManager.GetString("CategoryId", resourceCulture);
            }
        }
        
        public static string ItemDayPrice {
            get {
                return ResourceManager.GetString("ItemDayPrice", resourceCulture);
            }
        }
        
        public static string ItemWeekPrice {
            get {
                return ResourceManager.GetString("ItemWeekPrice", resourceCulture);
            }
        }
        
        public static string ItemMonthPrice {
            get {
                return ResourceManager.GetString("ItemMonthPrice", resourceCulture);
            }
        }
        
        public static string ProductDescriptionId {
            get {
                return ResourceManager.GetString("ProductDescriptionId", resourceCulture);
            }
        }
        
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
    }
}
