//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Shared {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resources.Views.Shared.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        public static string BackToProfile {
            get {
                return ResourceManager.GetString("BackToProfile", resourceCulture);
            }
        }
        
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        public static string ChoosePictures {
            get {
                return ResourceManager.GetString("ChoosePictures", resourceCulture);
            }
        }
        
        public static string NoFileChosen {
            get {
                return ResourceManager.GetString("NoFileChosen", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string SearchPlaceHolder {
            get {
                return ResourceManager.GetString("SearchPlaceHolder", resourceCulture);
            }
        }
        
        public static string BackToFullList {
            get {
                return ResourceManager.GetString("BackToFullList", resourceCulture);
            }
        }
        
        public static string ErrorMessage_MaxLength {
            get {
                return ResourceManager.GetString("ErrorMessage_MaxLength", resourceCulture);
            }
        }
        
        public static string ErrorMessage_MinLength {
            get {
                return ResourceManager.GetString("ErrorMessage_MinLength", resourceCulture);
            }
        }
        
        public static string ErrorMessage_Required {
            get {
                return ResourceManager.GetString("ErrorMessage_Required", resourceCulture);
            }
        }
        
        public static string ErrorMessage_StringLengthMax {
            get {
                return ResourceManager.GetString("ErrorMessage_StringLengthMax", resourceCulture);
            }
        }
        
        public static string ErrorMessage_StringLengthMinMax {
            get {
                return ResourceManager.GetString("ErrorMessage_StringLengthMinMax", resourceCulture);
            }
        }
        
        public static string ErrorMessage_Range {
            get {
                return ResourceManager.GetString("ErrorMessage_Range", resourceCulture);
            }
        }
    }
}
