//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Account.Manage {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Manage {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Manage() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resources.Views.Account.Manage.Manage", typeof(Manage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ManageYourAccount {
            get {
                return ResourceManager.GetString("ManageYourAccount", resourceCulture);
            }
        }
        
        public static string ChangeAccountSettings {
            get {
                return ResourceManager.GetString("ChangeAccountSettings", resourceCulture);
            }
        }
        
        public static string Iown {
            get {
                return ResourceManager.GetString("Iown", resourceCulture);
            }
        }
        
        public static string Irent {
            get {
                return ResourceManager.GetString("Irent", resourceCulture);
            }
        }
        
        public static string MyCompanies {
            get {
                return ResourceManager.GetString("MyCompanies", resourceCulture);
            }
        }
        
        public static string Bookings {
            get {
                return ResourceManager.GetString("Bookings", resourceCulture);
            }
        }
        
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        public static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        public static string BookingsAsRenter {
            get {
                return ResourceManager.GetString("BookingsAsRenter", resourceCulture);
            }
        }
        
        public static string BookingsAsOwner {
            get {
                return ResourceManager.GetString("BookingsAsOwner", resourceCulture);
            }
        }
        
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string Two_factor {
            get {
                return ResourceManager.GetString("Two-factor", resourceCulture);
            }
        }
        
        public static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        public static string ExternalLogins {
            get {
                return ResourceManager.GetString("ExternalLogins", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string ManageEmail {
            get {
                return ResourceManager.GetString("ManageEmail", resourceCulture);
            }
        }
        
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        public static string UpdatePassword {
            get {
                return ResourceManager.GetString("UpdatePassword", resourceCulture);
            }
        }
        
        public static string PersonalText {
            get {
                return ResourceManager.GetString("PersonalText", resourceCulture);
            }
        }
        
        public static string PersonalTextBold {
            get {
                return ResourceManager.GetString("PersonalTextBold", resourceCulture);
            }
        }
        
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
    }
}
